services:

  engine:
    image: ghcr.io/gostratacore/gostratumengine:latest

    restart: unless-stopped

    ports:
      - "3333:3333"
      - "8080:8080"

    volumes:
      - ${APP_DATA_DIR}/data:/pool
