version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: engine
      APP_PORT: 8080
      JWT_SECRET: "${JWT_SECRET}"
    networks:
      - umbrel_main_network

  engine:
    image: ghcr.io/gostratacore/gostratumengine:1.2.4
    restart: unless-stopped

    ports:
      - "3333:3333"
      - "8080:8080"

    volumes:
      - ${APP_DATA_DIR}/data:/pool

    environment:
      - APP_DATA_DIR=${APP_DATA_DIR}

    networks:
      - umbrel_main_network   # <-- ADD THIS

networks:
  umbrel_main_network:
    external: true
    name: umbrel_main_network
